### ISSUE TITLE
Peer review

### ISSUE THREAD

**Issue by sebastianbragam** [MarcoSavarin0/Mercado_Liebre_DH#1]
1. Cumple.
2. No cumple. Falta margen y los 2em.
3. Cumple.
4. Cumple.
5. Cumple.
6. No cumple en ninguna de las dos pantallas.
7. No cumple. No es un formulario.
8. Cumple.
9. Lindo diseño. Buenas animaciones.
10. Algunos puntos por mejorar de las consignas. Los tamaños de las cosas no cambian para distintas resoluciones.

**Comment by MarcoSavarin0** [comment]
completado
